# Generated by Django 6.0 on 2026-01-09 10:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departmentApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('total_days', models.IntegerField(default=0, editable=False)),
                ('objectives', models.JSONField(default=list)),
                ('prerequisites', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_programs', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_programs', to='departmentApp.department')),
            ],
            options={
                'verbose_name': 'Mentorship Program',
                'verbose_name_plural': 'Mentorship Programs',
                'ordering': ['department__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('goals', models.JSONField(default=list)),
                ('achievements', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mentorships', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorships', to='departmentApp.department')),
                ('mentee', models.ForeignKey(limit_choices_to={'role': 'mentee'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentorships_as_mentee', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentorships_as_mentor', to=settings.AUTH_USER_MODEL)),
                ('current_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_mentorships', to='mentorshipApp.mentorshipprogram')),
                ('programs', models.ManyToManyField(blank=True, related_name='mentorships', to='mentorshipApp.mentorshipprogram')),
            ],
            options={
                'verbose_name': 'Mentorship',
                'verbose_name_plural': 'Mentorships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipProgramProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused')], default='not_started', max_length=20)),
                ('sessions_completed', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_progress', to='mentorshipApp.mentorship')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='mentorshipApp.mentorshipprogram')),
            ],
            options={
                'verbose_name': 'Program Progress',
                'verbose_name_plural': 'Program Progress',
                'ordering': ['program__name'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_type', models.CharField(choices=[('mentor', 'Mentor'), ('mentee', 'Mentee')], max_length=10)),
                ('rating', models.IntegerField(help_text='Overall rating (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_rating', models.IntegerField(help_text='Communication rating (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('knowledge_rating', models.IntegerField(help_text='Knowledge/expertise rating (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('helpfulness_rating', models.IntegerField(help_text='Helpfulness rating (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField()),
                ('would_recommend', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mentorshipApp.mentorship')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentorship Review',
                'verbose_name_plural': 'Mentorship Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramSessionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('session_type', models.CharField(choices=[('video', 'Video Call'), ('in_person', 'In Person'), ('phone', 'Phone Call'), ('chat', 'Chat'), ('workshop', 'Workshop'), ('training', 'Training'), ('assessment', 'Assessment')], default='video', max_length=20)),
                ('description', models.TextField()),
                ('objectives', models.JSONField(default=list)),
                ('requirements', models.JSONField(default=list)),
                ('duration_minutes', models.IntegerField(help_text='Duration in minutes (minimum 15)', validators=[django.core.validators.MinValueValidator(15)])),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program Session Template',
                'verbose_name_plural': 'Program Session Templates',
                'ordering': ['order'],
                'unique_together': {('title', 'order')},
            },
        ),
        migrations.CreateModel(
            name='MentorshipSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_session_number', models.IntegerField(default=1, help_text='Session number within this program', validators=[django.core.validators.MinValueValidator(1)])),
                ('overall_session_number', models.IntegerField(default=1, help_text='Overall session number across all programs', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('actual_date', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(15)])),
                ('agenda', models.TextField(blank=True)),
                ('objectives', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('action_items', models.JSONField(default=list)),
                ('mentor_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('mentor_feedback', models.TextField(blank=True)),
                ('mentee_feedback', models.TextField(blank=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_sessions', to=settings.AUTH_USER_MODEL)),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mentorshipApp.mentorship')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mentorshipApp.mentorshipprogram')),
                ('program_progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='mentorshipApp.mentorshipprogramprogress')),
                ('session_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentorship_sessions', to='mentorshipApp.programsessiontemplate')),
            ],
            options={
                'verbose_name': 'Mentorship Session',
                'verbose_name_plural': 'Mentorship Sessions',
                'ordering': ['program_session_number'],
            },
        ),
        migrations.AddField(
            model_name='mentorshipprogram',
            name='session_templates',
            field=models.ManyToManyField(related_name='programs', to='mentorshipApp.programsessiontemplate'),
        ),
        migrations.CreateModel(
            name='MentorshipMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('note', 'Note'), ('update', 'Update'), ('reminder', 'Reminder')], default='note', max_length=20)),
                ('attachments', models.JSONField(default=list, help_text='List of attachment URLs')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_messages', to='mentorshipApp.mentorship')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_mentorship_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentorship Message',
                'verbose_name_plural': 'Mentorship Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mentorship', 'is_read'], name='mentorshipA_mentors_36b306_idx'), models.Index(fields=['created_at'], name='mentorshipA_created_11d9db_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mentorship',
            index=models.Index(fields=['status'], name='mentorshipA_status_a950b3_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorship',
            index=models.Index(fields=['start_date'], name='mentorshipA_start_d_d642c4_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorship',
            index=models.Index(fields=['department'], name='mentorshipA_departm_43d5f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mentorship',
            unique_together={('mentor', 'mentee', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='mentorshipprogramprogress',
            unique_together={('mentorship', 'program')},
        ),
        migrations.AddIndex(
            model_name='mentorshipreview',
            index=models.Index(fields=['mentorship'], name='mentorshipA_mentors_55a94f_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshipreview',
            index=models.Index(fields=['rating'], name='mentorshipA_rating_513f2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mentorshipreview',
            unique_together={('mentorship', 'reviewer')},
        ),
        migrations.AddIndex(
            model_name='mentorshipsession',
            index=models.Index(fields=['mentorship', 'program', 'status'], name='mentorshipA_mentors_327a38_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshipsession',
            index=models.Index(fields=['scheduled_date'], name='mentorshipA_schedul_8c5de1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mentorshipsession',
            unique_together={('mentorship', 'program', 'program_session_number')},
        ),
        migrations.AddIndex(
            model_name='mentorshipprogram',
            index=models.Index(fields=['status'], name='mentorshipA_status_d70093_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshipprogram',
            index=models.Index(fields=['department'], name='mentorshipA_departm_6cdae3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mentorshipprogram',
            unique_together={('name', 'department')},
        ),
    ]
