# Generated by Django 6.0 on 2026-01-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorshipApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programsessiontemplate',
            unique_together=set(),
        ),
    ]
