# Generated by Django 6.0 on 2026-01-09 13:10

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorshipApp', '0002_alter_programsessiontemplate_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='programsessiontemplate',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('order'), name='unique_title_order_case_insensitive'),
        ),
    ]
