# Generated by Django 6.0 on 2026-01-05 09:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_message', 'New Message'), ('case_assigned', 'Case Assigned'), ('case_status_changed', 'Case Status Changed')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_notifications', to=settings.AUTH_USER_MODEL)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='mentoshipApp.chatroom')),
            ],
            options={
                'verbose_name': 'Chat Notification',
                'verbose_name_plural': 'Chat Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('sessions_completed', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('rating', models.DecimalField(blank=True, decimal_places=2, help_text='Overall mentorship rating (0-5)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField(blank=True, help_text='Overall feedback about the mentorship', null=True)),
                ('goals', models.JSONField(default=list, help_text='Mentorship goals set at the beginning')),
                ('achievements', models.JSONField(default=list, help_text='Goals achieved during mentorship')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the mentorship', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this mentorship', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mentorships', to=settings.AUTH_USER_MODEL)),
                ('mentee', models.ForeignKey(limit_choices_to={'role': 'mentee'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentorships_as_mentee', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentorships_as_mentor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentorship',
                'verbose_name_plural': 'Mentorships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatroom',
            name='mentorship',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='mentoshipApp.mentorship'),
        ),
        migrations.CreateModel(
            name='MentorshipProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('total_sessions', models.IntegerField(default=12, help_text='Total number of sessions in this program', validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_weeks', models.IntegerField(default=12, help_text='Program duration in weeks', validators=[django.core.validators.MinValueValidator(1)])),
                ('objectives', models.JSONField(default=list, help_text='List of program objectives')),
                ('requirements', models.JSONField(default=list, help_text='List of requirements for mentors/mentees')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentorship Program',
                'verbose_name_plural': 'Mentorship Programs',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='mentorship',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorships', to='mentoshipApp.mentorshipprogram'),
        ),
        migrations.CreateModel(
            name='MentorshipReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_type', models.CharField(choices=[('mentor', 'Mentor'), ('mentee', 'Mentee')], max_length=10)),
                ('rating', models.IntegerField(help_text='Overall rating (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_rating', models.IntegerField(help_text='Communication rating (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('knowledge_rating', models.IntegerField(help_text='Knowledge/expertise rating (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('helpfulness_rating', models.IntegerField(help_text='Helpfulness rating (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField()),
                ('would_recommend', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mentoshipApp.mentorship')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentorship Review',
                'verbose_name_plural': 'Mentorship Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.IntegerField(help_text='Sequential session number', validators=[django.core.validators.MinValueValidator(1)])),
                ('session_type', models.CharField(choices=[('video', 'Video Call'), ('in_person', 'In Person'), ('phone', 'Phone Call'), ('chat', 'Chat')], default='video', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('actual_date', models.DateTimeField(blank=True, help_text='Actual session date if different from scheduled', null=True)),
                ('duration_minutes', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)])),
                ('agenda', models.TextField(blank=True, help_text='Session agenda or topics to cover')),
                ('notes', models.TextField(blank=True, help_text='Session notes and discussion points')),
                ('action_items', models.JSONField(default=list, help_text='Action items from the session')),
                ('mentor_rating', models.IntegerField(blank=True, help_text="Mentee's rating of the session (1-5)", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('mentor_feedback', models.TextField(blank=True, help_text="Mentor's feedback about the session")),
                ('mentee_feedback', models.TextField(blank=True, help_text="Mentee's feedback about the session")),
                ('meeting_link', models.URLField(blank=True, help_text='Video call link if applicable', null=True)),
                ('location', models.CharField(blank=True, help_text='Location for in-person meetings', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mentoshipApp.mentorship')),
            ],
            options={
                'verbose_name': 'Mentorship Session',
                'verbose_name_plural': 'Mentorship Sessions',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('image', 'Image'), ('system', 'System')], default='text', max_length=10)),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat_attachments/')),
                ('is_read', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mentoshipApp.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='mentoshipApp.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_read_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Read Status',
                'verbose_name_plural': 'Message Read Statuses',
            },
        ),
        migrations.CreateModel(
            name='MentorshipMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('attachments', models.JSONField(default=list, help_text='List of attachment URLs')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mentoshipApp.mentorship')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_mentorship_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentorship Message',
                'verbose_name_plural': 'Mentorship Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mentorship', 'is_read'], name='mentoshipAp_mentors_f258f1_idx'), models.Index(fields=['created_at'], name='mentoshipAp_created_4b789c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mentorshipprogram',
            index=models.Index(fields=['status'], name='mentoshipAp_status_3d3fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshipprogram',
            index=models.Index(fields=['name'], name='mentoshipAp_name_8bb7b2_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorship',
            index=models.Index(fields=['status'], name='mentoshipAp_status_5ea1af_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorship',
            index=models.Index(fields=['mentor', 'status'], name='mentoshipAp_mentor__99a814_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorship',
            index=models.Index(fields=['mentee', 'status'], name='mentoshipAp_mentee__501daa_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorship',
            index=models.Index(fields=['start_date'], name='mentoshipAp_start_d_dfb7cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mentorship',
            unique_together={('mentor', 'mentee', 'program')},
        ),
        migrations.AddIndex(
            model_name='mentorshipreview',
            index=models.Index(fields=['mentorship'], name='mentoshipAp_mentors_84b832_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshipreview',
            index=models.Index(fields=['rating'], name='mentoshipAp_rating_504cae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mentorshipreview',
            unique_together={('mentorship', 'reviewer')},
        ),
        migrations.AddIndex(
            model_name='mentorshipsession',
            index=models.Index(fields=['mentorship', 'status'], name='mentoshipAp_mentors_d2f699_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshipsession',
            index=models.Index(fields=['scheduled_date'], name='mentoshipAp_schedul_07bd02_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshipsession',
            index=models.Index(fields=['status'], name='mentoshipAp_status_cb3f33_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mentorshipsession',
            unique_together={('mentorship', 'session_number')},
        ),
        migrations.AlterUniqueTogether(
            name='messagereadstatus',
            unique_together={('message', 'user')},
        ),
    ]
