# Generated by Django 6.0 on 2026-01-08 12:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departmentApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('department', models.CharField(help_text='Department this program belongs to', max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('total_days', models.IntegerField(default=0, editable=False, help_text='Auto-calculated total days based on session durations')),
                ('objectives', models.JSONField(default=list, help_text='Overall program objectives')),
                ('prerequisites', models.JSONField(default=list, help_text='Prerequisites for joining this program')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentorship Program',
                'verbose_name_plural': 'Mentorship Programs',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('total_sessions_required', models.IntegerField(default=0, editable=False)),
                ('sessions_completed', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('goals', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mentorships', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mentorships', to='departmentApp.department')),
                ('mentee', models.ForeignKey(limit_choices_to={'role': 'mentee'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentorships_as_mentee', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentorships_as_mentor', to=settings.AUTH_USER_MODEL)),
                ('completed_programs', models.ManyToManyField(blank=True, related_name='completed_by_mentorships', to='mentoshipApp.mentorshipprogram')),
                ('current_program', models.ForeignKey(blank=True, help_text='Current program being worked on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_mentorships', to='mentoshipApp.mentorshipprogram')),
                ('programs', models.ManyToManyField(blank=True, related_name='active_mentorships', to='mentoshipApp.mentorshipprogram')),
            ],
            options={
                'verbose_name': 'Mentorship',
                'verbose_name_plural': 'Mentorships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipProgramProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused')], default='not_started', max_length=20)),
                ('sessions_completed', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_progress', to='mentoshipApp.mentorship')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_progress', to='mentoshipApp.mentorshipprogram')),
            ],
            options={
                'verbose_name': 'Mentorship Program Progress',
                'verbose_name_plural': 'Mentorship Program Progress',
                'ordering': ['program'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_type', models.CharField(choices=[('mentor', 'Mentor'), ('mentee', 'Mentee')], max_length=10)),
                ('rating', models.IntegerField(help_text='Overall rating (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_rating', models.IntegerField(help_text='Communication rating (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('knowledge_rating', models.IntegerField(help_text='Knowledge/expertise rating (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('helpfulness_rating', models.IntegerField(help_text='Helpfulness rating (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField()),
                ('would_recommend', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mentoshipApp.mentorship')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentorship Review',
                'verbose_name_plural': 'Mentorship Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramSessionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('session_type', models.CharField(choices=[('video', 'Video Call'), ('in_person', 'In Person'), ('phone', 'Phone Call'), ('chat', 'Chat'), ('workshop', 'Workshop'), ('training', 'Training'), ('assessment', 'Assessment')], default='video', max_length=20)),
                ('description', models.TextField()),
                ('objectives', models.JSONField(default=list, help_text='Session objectives/learning outcomes')),
                ('requirements', models.JSONField(default=list, help_text='Session requirements')),
                ('duration_minutes', models.IntegerField(help_text='Duration in minutes (minimum 15)', validators=[django.core.validators.MinValueValidator(15)])),
                ('order', models.IntegerField(help_text='Session order in the program (1, 2, 3...)', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program Session Template',
                'verbose_name_plural': 'Program Session Templates',
                'ordering': ['order'],
                'unique_together': {('title', 'order')},
            },
        ),
        migrations.CreateModel(
            name='MentorshipSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_session_number', models.IntegerField(default=1, help_text='Session number within this program', validators=[django.core.validators.MinValueValidator(1)])),
                ('session_number', models.IntegerField(help_text='Sequential session number in this mentorship', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('actual_date', models.DateTimeField(blank=True, help_text='Actual session date if different from scheduled', null=True)),
                ('duration_minutes', models.IntegerField(default=60, help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(15)])),
                ('agenda', models.TextField(blank=True, help_text='Specific agenda for this session')),
                ('objectives', models.JSONField(default=list, help_text='Session objectives to cover')),
                ('requirements', models.JSONField(default=list, help_text='Requirements for this session')),
                ('notes', models.TextField(blank=True, help_text='Session notes and discussion points')),
                ('action_items', models.JSONField(default=list, help_text='Action items from the session')),
                ('mentor_rating', models.IntegerField(blank=True, help_text="Mentee's rating of the session (1-5)", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('mentor_feedback', models.TextField(blank=True, help_text="Mentor's feedback about the session")),
                ('mentee_feedback', models.TextField(blank=True, help_text="Mentee's feedback about the session")),
                ('meeting_link', models.URLField(blank=True, help_text='Video call link if applicable', null=True)),
                ('location', models.CharField(blank=True, help_text='Location for in-person meetings', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, help_text='User who marked this session as completed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_sessions', to=settings.AUTH_USER_MODEL)),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mentoshipApp.mentorship')),
                ('program', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mentoshipApp.mentorshipprogram')),
                ('program_progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mentoshipApp.mentorshipprogramprogress')),
                ('session_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentorship_sessions', to='mentoshipApp.programsessiontemplate')),
            ],
            options={
                'verbose_name': 'Mentorship Session',
                'verbose_name_plural': 'Mentorship Sessions',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.AddField(
            model_name='mentorshipprogram',
            name='session_templates',
            field=models.ManyToManyField(help_text='Sessions included in this program', related_name='programs', to='mentoshipApp.programsessiontemplate'),
        ),
        migrations.CreateModel(
            name='MentorshipMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('note', 'Note'), ('update', 'Update'), ('reminder', 'Reminder')], default='note', max_length=20)),
                ('attachments', models.JSONField(default=list, help_text='List of attachment URLs')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_messages', to='mentoshipApp.mentorship')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_mentorship_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentorship Message',
                'verbose_name_plural': 'Mentorship Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mentorship', 'is_read'], name='mentoshipAp_mentors_f258f1_idx'), models.Index(fields=['created_at'], name='mentoshipAp_created_4b789c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mentorship',
            index=models.Index(fields=['status'], name='mentoshipAp_status_5ea1af_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorship',
            index=models.Index(fields=['start_date'], name='mentoshipAp_start_d_dfb7cc_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorship',
            index=models.Index(fields=['-created_at'], name='mentoshipAp_created_be4cdf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mentorship',
            unique_together={('mentor', 'mentee', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='mentorshipprogramprogress',
            unique_together={('mentorship', 'program')},
        ),
        migrations.AddIndex(
            model_name='mentorshipreview',
            index=models.Index(fields=['mentorship'], name='mentoshipAp_mentors_84b832_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshipreview',
            index=models.Index(fields=['rating'], name='mentoshipAp_rating_504cae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mentorshipreview',
            unique_together={('mentorship', 'reviewer')},
        ),
        migrations.AddIndex(
            model_name='mentorshipsession',
            index=models.Index(fields=['mentorship', 'status'], name='mentoshipAp_mentors_d2f699_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshipsession',
            index=models.Index(fields=['scheduled_date'], name='mentoshipAp_schedul_07bd02_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshipsession',
            index=models.Index(fields=['status'], name='mentoshipAp_status_cb3f33_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshipsession',
            index=models.Index(fields=['session_template'], name='mentoshipAp_session_0bddc8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mentorshipsession',
            unique_together={('mentorship', 'session_number')},
        ),
        migrations.AddIndex(
            model_name='mentorshipprogram',
            index=models.Index(fields=['status'], name='mentoshipAp_status_3d3fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshipprogram',
            index=models.Index(fields=['name'], name='mentoshipAp_name_8bb7b2_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshipprogram',
            index=models.Index(fields=['department'], name='mentoshipAp_departm_25b3fc_idx'),
        ),
    ]
