# Generated by Django 6.0 on 2026-01-05 15:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoshipApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramSessionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('session_type', models.CharField(choices=[('video', 'Video Call'), ('in_person', 'In Person'), ('phone', 'Phone Call'), ('chat', 'Chat'), ('workshop', 'Workshop'), ('training', 'Training'), ('assessment', 'Assessment')], default='video', max_length=20)),
                ('description', models.TextField()),
                ('objectives', models.JSONField(default=list, help_text='Session objectives/learning outcomes')),
                ('requirements', models.JSONField(default=list, help_text='Session requirements')),
                ('duration_minutes', models.IntegerField(help_text='Duration in minutes (minimum 15)', validators=[django.core.validators.MinValueValidator(15)])),
                ('order', models.IntegerField(help_text='Session order in the program (1, 2, 3...)', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program Session Template',
                'verbose_name_plural': 'Program Session Templates',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='mentorshipprogram',
            options={'ordering': ['department', 'name'], 'verbose_name': 'Mentorship Program', 'verbose_name_plural': 'Mentorship Programs'},
        ),
        migrations.RemoveField(
            model_name='mentorship',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='mentorshipprogram',
            name='duration_weeks',
        ),
        migrations.RemoveField(
            model_name='mentorshipprogram',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='mentorshipprogram',
            name='total_sessions',
        ),
        migrations.RemoveField(
            model_name='mentorshipsession',
            name='session_type',
        ),
        migrations.AddField(
            model_name='mentorship',
            name='actual_end_date',
            field=models.DateField(blank=True, help_text='Actual completion date', null=True),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='expected_end_date',
            field=models.DateField(blank=True, help_text='Auto-calculated based on program duration', null=True),
        ),
        migrations.AddField(
            model_name='mentorshipprogram',
            name='prerequisites',
            field=models.JSONField(default=list, help_text='Prerequisites for joining this program'),
        ),
        migrations.AddField(
            model_name='mentorshipprogram',
            name='total_days',
            field=models.IntegerField(default=0, editable=False, help_text='Auto-calculated total days based on session durations'),
        ),
        migrations.AddField(
            model_name='mentorshipsession',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='User who marked this session as completed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorshipsession',
            name='objectives',
            field=models.JSONField(default=list, help_text='Session objectives to cover'),
        ),
        migrations.AddField(
            model_name='mentorshipsession',
            name='requirements',
            field=models.JSONField(default=list, help_text='Requirements for this session'),
        ),
        migrations.AlterField(
            model_name='mentorshipprogram',
            name='objectives',
            field=models.JSONField(default=list, help_text='Overall program objectives'),
        ),
        migrations.AlterField(
            model_name='mentorshipsession',
            name='agenda',
            field=models.TextField(blank=True, help_text='Specific agenda for this session'),
        ),
        migrations.AlterField(
            model_name='mentorshipsession',
            name='duration_minutes',
            field=models.IntegerField(default=60, help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='mentorshipsession',
            name='session_number',
            field=models.IntegerField(help_text='Sequential session number in this mentorship', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='mentorship',
            index=models.Index(fields=['program'], name='mentoshipAp_program_84d6cb_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active'], name='mentoshipAp_is_acti_7ad436_idx'),
        ),
        migrations.AddField(
            model_name='mentorshipprogram',
            name='department',
            field=models.ForeignKey(default=None, help_text='Department this program belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='mentoshipApp.department'),
        ),
        migrations.AlterUniqueTogether(
            name='programsessiontemplate',
            unique_together={('title', 'order')},
        ),
        migrations.AddField(
            model_name='mentorshipprogram',
            name='session_templates',
            field=models.ManyToManyField(help_text='Sessions included in this program', related_name='programs', to='mentoshipApp.programsessiontemplate'),
        ),
        migrations.AddField(
            model_name='mentorshipsession',
            name='session_template',
            field=models.ForeignKey(help_text='Session template this session is based on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentorship_sessions', to='mentoshipApp.programsessiontemplate'),
        ),
        migrations.AddIndex(
            model_name='mentorshipprogram',
            index=models.Index(fields=['department'], name='mentoshipAp_departm_e85177_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshipsession',
            index=models.Index(fields=['session_template'], name='mentoshipAp_session_0bddc8_idx'),
        ),
    ]
