# Generated by Django 6.0 on 2026-01-06 15:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoshipApp', '0002_department_programsessiontemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('image', 'Image'), ('system', 'System'), ('announcement', 'Announcement')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='group_chat_attachments/')),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Group Chat Message',
                'verbose_name_plural': 'Group Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('member', 'Member'), ('guest', 'Guest')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('is_muted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Group Chat Participant',
                'verbose_name_plural': 'Group Chat Participants',
            },
        ),
        migrations.CreateModel(
            name='GroupChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('chat_type', models.CharField(choices=[('one_on_one', 'One-on-One Chat'), ('mentorship_group', 'Mentorship Group Chat'), ('department_group', 'Department Group Chat'), ('cross_department', 'Cross-Department Chat')], default='mentorship_group', max_length=50)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Group Chat Room',
                'verbose_name_plural': 'Group Chat Rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMessageReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Group Message Read Status',
                'verbose_name_plural': 'Group Message Read Statuses',
            },
        ),
        migrations.RemoveIndex(
            model_name='department',
            name='mentoshipAp_is_acti_7ad436_idx',
        ),
        migrations.AlterField(
            model_name='mentorshipprogram',
            name='department',
            field=models.CharField(help_text='Department this program belongs to', max_length=100),
        ),
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RenameIndex(
            model_name='mentorshipprogram',
            new_name='mentoshipAp_departm_25b3fc_idx',
            old_name='mentoshipAp_departm_e85177_idx',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='chat_type',
            field=models.CharField(choices=[('mentor_mentee', 'Mentor-Mentee'), ('mentee_admin', 'Mentee-Admin'), ('mentee_hr', 'Mentee-HR'), ('mentor_admin', 'Mentor-Admin'), ('mentor_hr', 'Mentor-HR'), ('admin_hr', 'Admin-HR')], default='mentor_mentee', max_length=20),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='mentorship',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_on_one_chat', to='mentoshipApp.mentorship'),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('user1', 'user2')},
        ),
        migrations.AddField(
            model_name='groupchatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='mentoshipApp.groupchatmessage'),
        ),
        migrations.AddField(
            model_name='groupchatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_group_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupchatparticipant',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_group_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupchatparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_chat_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupchatroom',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_group_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupchatroom',
            name='mentorship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_chats', to='mentoshipApp.mentorship'),
        ),
        migrations.AddField(
            model_name='groupchatparticipant',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participants', to='mentoshipApp.groupchatroom'),
        ),
        migrations.AddField(
            model_name='groupchatmessage',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='mentoshipApp.groupchatroom'),
        ),
        migrations.AddField(
            model_name='groupmessagereadstatus',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='mentoshipApp.groupchatmessage'),
        ),
        migrations.AddField(
            model_name='groupmessagereadstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_message_read_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AddIndex(
            model_name='groupchatparticipant',
            index=models.Index(fields=['chat_room', 'user'], name='mentoshipAp_chat_ro_1ba8c2_idx'),
        ),
        migrations.AddIndex(
            model_name='groupchatparticipant',
            index=models.Index(fields=['role'], name='mentoshipAp_role_1ba6f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupchatparticipant',
            unique_together={('chat_room', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='groupmessagereadstatus',
            unique_together={('message', 'user')},
        ),
    ]
