# Generated by Django 6.0 on 2026-01-07 14:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentoshipApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_type', models.CharField(choices=[('mentor_mentee', 'Mentor-Mentee'), ('mentee_admin', 'Mentee-Admin'), ('mentee_hr', 'Mentee-HR'), ('mentor_admin', 'Mentor-Admin'), ('mentor_hr', 'Mentor-HR'), ('admin_hr', 'Admin-HR')], default='mentor_mentee', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentorship', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_on_one_chat', to='mentoshipApp.mentorship')),
                ('user1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Room',
                'verbose_name_plural': 'Chat Rooms',
                'ordering': ['-updated_at'],
                'unique_together': {('user1', 'user2')},
            },
        ),
        migrations.CreateModel(
            name='GroupChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('chat_type', models.CharField(choices=[('one_on_one', 'One-on-One Chat'), ('mentorship_group', 'Mentorship Group Chat'), ('department_group', 'Department Group Chat'), ('cross_department', 'Cross-Department Chat')], default='mentorship_group', max_length=50)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_group_chats', to=settings.AUTH_USER_MODEL)),
                ('mentorship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_chats', to='mentoshipApp.mentorship')),
            ],
            options={
                'verbose_name': 'Group Chat Room',
                'verbose_name_plural': 'Group Chat Rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('member', 'Member'), ('guest', 'Guest')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_group_participants', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_chat_participations', to=settings.AUTH_USER_MODEL)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participants', to='chatApp.groupchatroom')),
            ],
            options={
                'verbose_name': 'Group Chat Participant',
                'verbose_name_plural': 'Group Chat Participants',
            },
        ),
        migrations.CreateModel(
            name='GroupChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('image', 'Image'), ('system', 'System'), ('announcement', 'Announcement')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='group_chat_attachments/')),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chatApp.groupchatmessage')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_group_messages', to=settings.AUTH_USER_MODEL)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='chatApp.groupchatroom')),
            ],
            options={
                'verbose_name': 'Group Chat Message',
                'verbose_name_plural': 'Group Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMessageReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='chatApp.groupchatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_message_read_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Message Read Status',
                'verbose_name_plural': 'Group Message Read Statuses',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('image', 'Image'), ('system', 'System')], default='text', max_length=10)),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat_attachments/')),
                ('is_read', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatApp.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='chatApp.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_read_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Read Status',
                'verbose_name_plural': 'Message Read Statuses',
            },
        ),
        migrations.AddIndex(
            model_name='groupchatroom',
            index=models.Index(fields=['chat_type'], name='chatApp_gro_chat_ty_c49624_idx'),
        ),
        migrations.AddIndex(
            model_name='groupchatroom',
            index=models.Index(fields=['department'], name='chatApp_gro_departm_28e14b_idx'),
        ),
        migrations.AddIndex(
            model_name='groupchatroom',
            index=models.Index(fields=['is_active', 'is_archived'], name='chatApp_gro_is_acti_851e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='groupchatparticipant',
            index=models.Index(fields=['chat_room', 'user'], name='chatApp_gro_chat_ro_e96a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='groupchatparticipant',
            index=models.Index(fields=['role'], name='chatApp_gro_role_354761_idx'),
        ),
        migrations.AddIndex(
            model_name='groupchatparticipant',
            index=models.Index(fields=['is_muted'], name='chatApp_gro_is_mute_da8eeb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupchatparticipant',
            unique_together={('chat_room', 'user')},
        ),
        migrations.AddIndex(
            model_name='groupchatmessage',
            index=models.Index(fields=['chat_room', 'created_at'], name='chatApp_gro_chat_ro_fe199f_idx'),
        ),
        migrations.AddIndex(
            model_name='groupchatmessage',
            index=models.Index(fields=['sender', 'created_at'], name='chatApp_gro_sender__1a5fd3_idx'),
        ),
        migrations.AddIndex(
            model_name='groupchatmessage',
            index=models.Index(fields=['is_deleted'], name='chatApp_gro_is_dele_330897_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessagereadstatus',
            index=models.Index(fields=['user', 'read_at'], name='chatApp_gro_user_id_828721_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmessagereadstatus',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat_room', 'created_at'], name='chatApp_mes_chat_ro_56f187_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'is_read'], name='chatApp_mes_sender__b02a1e_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereadstatus',
            index=models.Index(fields=['user', 'read_at'], name='chatApp_mes_user_id_dbac82_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereadstatus',
            unique_together={('message', 'user')},
        ),
    ]
