# Generated by Django 6.0 on 2026-01-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentApp', '0001_initial'),
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='work_mail_address',
        ),
        migrations.AddField(
            model_name='customuser',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='users', to='departmentApp.department'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('mentor', 'Mentor'), ('mentee', 'Mentee')], max_length=20),
        ),
    ]
