# Generated by Django 6.0 on 2026-01-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_customuser_work_mail_address_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='work_mail_address',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
