# Generated by Django 6.0 on 2026-01-07 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentApp', '0001_initial'),
        ('userApp', '0004_alter_customuser_work_mail_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='departmentApp.department'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='departmentApp.department'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('mentor', 'Mentor'), ('mentee', 'Mentee'), ('hr', 'HR')], default='mentee', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='work_mail_address',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
