# Generated by Django 6.0 on 2026-01-07 18:11

import userApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0005_customuser_department_alter_customuser_departments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='work_mail_address',
            field=models.CharField(help_text='Work email address with custom domain format', max_length=255, unique=True, validators=[userApp.models.WorkEmailValidator()]),
        ),
    ]
