# Generated by Django 6.0 on 2026-01-07 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departmentApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('module_type', models.CharField(choices=[('core', 'Core'), ('department', 'Department-Specific')], default='core', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('duration_minutes', models.IntegerField(default=30, help_text='Estimated completion time in minutes')),
                ('content', models.JSONField(default=list, help_text='List of topics/sections')),
                ('resources', models.JSONField(default=list, help_text='Links to documents, videos, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_modules', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(blank=True, related_name='modules', to='departmentApp.department')),
            ],
            options={
                'verbose_name': 'Onboarding Module',
                'verbose_name_plural': 'Onboarding Modules',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField()),
                ('original_due_date', models.DateTimeField(help_text='Original due date before any extensions')),
                ('is_extended', models.BooleanField(default=False)),
                ('extension_reason', models.TextField(blank=True, help_text='Reason for extension', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extension_granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_extensions', to=settings.AUTH_USER_MODEL)),
                ('mentee', models.ForeignKey(limit_choices_to={'role': 'mentee'}, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_deadlines', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='onboarding.onboardingmodule')),
            ],
            options={
                'verbose_name': 'Onboarding Deadline',
                'verbose_name_plural': 'Onboarding Deadlines',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('estimated_minutes', models.IntegerField(default=15, help_text='Estimated time to complete this item')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='onboarding.onboardingmodule')),
            ],
            options={
                'verbose_name': 'Checklist Item',
                'verbose_name_plural': 'Checklist Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MenteeOnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('paused', 'Paused'), ('needs_attention', 'Needs Attention'), ('off_track', 'Off Track')], default='not_started', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, help_text='Expected completion date', null=True)),
                ('notes', models.TextField(blank=True, help_text='Mentee notes or feedback', null=True)),
                ('time_spent_minutes', models.IntegerField(default=0, help_text='Time spent on this module')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who assigned this module', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_onboarding_modules', to=settings.AUTH_USER_MODEL)),
                ('mentee', models.ForeignKey(limit_choices_to={'role': 'mentee'}, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_progress', to='onboarding.onboardingmodule')),
            ],
            options={
                'verbose_name': 'Mentee Onboarding Progress',
                'verbose_name_plural': 'Mentee Onboarding Progress',
                'ordering': ['module__order'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('module_assigned', 'Module Assigned'), ('module_started', 'Module Started'), ('module_completed', 'Module Completed'), ('deadline_approaching', 'Deadline Approaching'), ('status_changed', 'Status Changed'), ('needs_attention', 'Needs Attention'), ('off_track', 'Off Track'), ('overdue', 'Overdue')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='onboarding.onboardingmodule')),
                ('related_progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='onboarding.menteeonboardingprogress')),
            ],
            options={
                'verbose_name': 'Onboarding Notification',
                'verbose_name_plural': 'Onboarding Notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MenteeChecklistProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_minutes', models.IntegerField(default=0, help_text='Time spent on this checklist item')),
                ('notes', models.TextField(blank=True, help_text='Notes about this checklist item', null=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_progress', to=settings.AUTH_USER_MODEL)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_completions', to='onboarding.onboardingchecklist')),
            ],
            options={
                'verbose_name': 'Checklist Progress',
                'verbose_name_plural': 'Checklist Progress',
                'indexes': [models.Index(fields=['mentee', 'is_completed'], name='onboarding__mentee__181ba9_idx'), models.Index(fields=['checklist_item', 'is_completed'], name='onboarding__checkli_dc7bd9_idx')],
                'unique_together': {('mentee', 'checklist_item')},
            },
        ),
        migrations.AddIndex(
            model_name='onboardingmodule',
            index=models.Index(fields=['module_type'], name='onboarding__module__519931_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingmodule',
            index=models.Index(fields=['is_active'], name='onboarding__is_acti_dc5dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingdeadline',
            index=models.Index(fields=['due_date'], name='onboarding__due_dat_236de9_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingdeadline',
            index=models.Index(fields=['mentee', 'due_date'], name='onboarding__mentee__7280d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='onboardingdeadline',
            unique_together={('module', 'mentee')},
        ),
        migrations.AddIndex(
            model_name='onboardingchecklist',
            index=models.Index(fields=['module', 'order'], name='onboarding__module__a6308f_idx'),
        ),
        migrations.AddIndex(
            model_name='menteeonboardingprogress',
            index=models.Index(fields=['mentee', 'status'], name='onboarding__mentee__33544c_idx'),
        ),
        migrations.AddIndex(
            model_name='menteeonboardingprogress',
            index=models.Index(fields=['status'], name='onboarding__status_35ccb0_idx'),
        ),
        migrations.AddIndex(
            model_name='menteeonboardingprogress',
            index=models.Index(fields=['due_date'], name='onboarding__due_dat_f30de3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menteeonboardingprogress',
            unique_together={('mentee', 'module')},
        ),
        migrations.AddIndex(
            model_name='onboardingnotification',
            index=models.Index(fields=['recipient', 'is_read'], name='onboarding__recipie_11b1e9_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingnotification',
            index=models.Index(fields=['sent_at'], name='onboarding__sent_at_c2ec9f_idx'),
        ),
    ]
